# 버전은 현재, 0.2가 권장사항입니다.
version: 0.2

# 빌드 단계별로 원하는 명령을 입력합니다.
phases:
  # 빌드 전 수행할 명령을 입력합니다.
  pre_build:
    commands:
      - echo CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS} >> .env
      - pwd
      - cat .env
# 빌드 결과물로 나온 아티팩트에 대한 정보를 제공합니다.
artifacts:
  # 빌드 환경에서 빌드 출력 결과물이 생성되는 위치를 나타냅니다.
  # '**/*'는 모든 파일을 재귀적으로 나타냅니다.
  files:
    - "**/*"